### ISSUE TITLE
Error message upon hitting play that 2nd lighting cannot be loaded as it is not in build settings

### ISSUE THREAD

**Issue by visualhippocracy** [laurenth-personal/lightmap-switching-tool#26]
Followed the steps as mentioned in the readme.
However upon hitting play an error is thrown that says: Scene 'Lighting_02' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...

I have correctly stored the lighting as when I change default lighting scenario on the lightswitcher script it does default to either lighting scenario 1 or 2 depending upon the setting

**Comment by visualhippocracy** [comment]
Lol Stupid me

**Comment by laurenth-personal** [comment]
I refreshed a little the readme file and included some explanations about this point :)
