### ISSUE TITLE
Have built and stored the lightmaps, but now cannot actually swap them

### ISSUE THREAD

**Issue by ChiefWickie** [laurenth-personal/lightmap-switching-tool#30]
Hi, this tool looks great =- just what a lot of people need I think!
Its all set up for me apart from the last step ("Now add an empty Gameobject to your scene and add a LightingScenarioSwitcher for previewing the switch").
I don't see anyway to add that component/script?
Beyond that switch UI, what is the method to be called to programmatically swap the lightmaps?

**Comment by laurenth-personal** [comment]
Oh right I have removed that component because it was just a very hard coded thing that switched when clicking.
You can do the same as the UI buttons do : reference the levellightmapdata and call LoadLightingScenario(index of the scenario)

**Comment by laurenth-personal** [comment]
Thanks for reporting this issue, I forgot to update the readme. Also see the other open issue you shouldn't call LoadLightingScenario too early (like in an awake method) otherwise the light probes might not be ready. I'll include that in the readme too.

**Comment by laurenth-personal** [comment]
I have updated the instructions :)

**Comment by ChiefWickie** [comment]
Sorry for delays in replying any of this @laurenth-personal ! Thats great for the conformation and changes. Keep up the good work! Its a nice project

**Comment by laurenth-personal** [comment]
Thanks :)
