### ISSUE TITLE
Problem with light probes

### ISSUE THREAD

**Issue by VitaliyVikulov-azur** [laurenth-personal/lightmap-switching-tool#31]
Hello, thank you for the great tool. I have a problem with light probes. It don't change if a scenario is changed. It take values from last baked data of the main scene.
Unity version 2019.4.16f1. I have in my project:
Scenes:
1. Main scene with static objects, 1 dynamic object and lighprobes. Lightmode is Subtractive.
2. Scene 2 with mixed directional light. Lightmode is Subtractive.
3. Scene 3 with mixed directional light. Lightmode is Subtractive.
I did everything that you wrote for setup. Light probes don't change if I try to change a scenario. It look the same as last baked result.
How I can fix that? Thanks.

**Comment by laurenth-personal** [comment]
Hi, thanks for reporting this issue. I have indeed never tested with subtractive mode so I'm not sure it works properly.
I will setup a test and get back to you but I night not have time to do that before next week.

**Comment by laurenth-personal** [comment]
Hi, I tried to do this in the test project provided :
- switch mixed mode of lighting 2 and 3 scenes to subtractive as well as for the static geometry scene, 
- set the directional lights to mixed if they're not already, 
- then open the static geometry scene only, select level lightmap data and in the component press build and when the bake is finished press store, did that for all lighting scenarios
- with only static geometry scene open press play and in play mode use the UI buttons to do the switch
This seems to work fine for me in the last unity 2019.4
There might be some misleading instructions in my readme ?
Can you try that in the test project and let me know if it works for you ?
