### ISSUE TITLE
Does this tool support URP or only built-in pipeline?

### ISSUE THREAD

**Issue by AUEzzat** [laurenth-personal/lightmap-switching-tool#34]

**Comment by laurenth-personal** [comment]
I am not very familiar with URP but this tool works on HDRP too so I think there are good chances it works with URP. 
There is some ongoing work on the master branch and the open-upm-release branch is probably the most reliable branch at this moment.

**Comment by AUEzzat** [comment]
Thank you for your quick reply, I have a building I try to bake night and day mode but as soon as I do that the baking finishes very quickly (a few seconds instead of hours) then the building is washed out like the second picture

![light-1](https://user-images.githubusercontent.com/11635578/162161754-86f7033d-07f7-41fa-bb7e-59c0d7cb71a2.PNG)

![image](https://user-images.githubusercontent.com/11635578/162161685-4257b310-b366-4002-b3f7-742cfa0621ee.png)

**Comment by laurenth-personal** [comment]
It's hard to tell from screenshots. 
If the bake was fast maybe it's because you did the same bake twice and unity just read the results from the cache.
For the rest do you think you could share your scene ?

**Comment by AUEzzat** [comment]
Unfortunately, I can't since the building is property owned.
But I will try to add the mesh to a new scene and see how it goes. 
Also, I will try to replicate it with another model to share it with you.

I appreciate your help so far; it is a great tool.

**Comment by AUEzzat** [comment]
It was a silly mistake that I forgot to mark the mesh as static.

**Comment by laurenth-personal** [comment]
Thank you for the update.
