### ISSUE TITLE
Can we bypass the initial lightmap.data asset ?

### ISSUE THREAD

**Issue by JAMS49** [laurenth-personal/lightmap-switching-tool#39]
So I have checked out that I can manually bake the lightmap in the scene and then store it using the lightmap switcher , when I switch it to day and night , I have scene that it actually replace the lightmap.data asset of the empty day scene on the baked lightmap tab . are those lightmap.data asset which are assigned automatically when switching between day and night are alone enough to properly arrange the lightmaps of the scene? because I have a large scene , I baked it and it's lightmap.data asset (before i've stored the bake info into another scene) is sooo large , like 370 mb or something , which causes crash in mobile for being too big . can I get rid of it somehow?

**Comment by laurenth-personal** [comment]
You can indeed remove the initial lighting data asset reference from the scene. Just go to the lighting window and click the lighting data asset reference and press delete on your keyboard.
This will not include those data when loading the scene (ambient light will be applied) and then only load the lighting data when using the lightmap switching tool.
You will have to do this after every lighting bake though since the asset will be referenced again after each bake.

**Comment by laurenth-personal** [comment]
Just thinking now that the problem with this is the light probes. They won't load correctly if your scene doesn't contain any initially. This might be possible to fix by calling this after loading the light probes : https://docs.unity3d.com/ScriptReference/LightProbes.Tetrahedralize.html
You don't need this function if the number of light probes is always the same, but if it changes (and removing the lighting data asset will make it change from 0 to something when you load) you need to call this function.

**Comment by laurenth-personal** [comment]
I could include this in the tool, but I'm not sure when. I would need time to test it.

**Comment by JAMS49** [comment]
> I could include this in the tool, but I'm not sure when. I would need time to test it.

Thanks a lot ! 

> You can indeed remove the initial lighting data asset reference from the scene. Just go to the lighting window and click the lighting data asset reference and press delete on your keyboard. This will not include those data when loading the scene (ambient light will be applied) and then only load the lighting data when using the lightmap switching tool. You will have to do this after every lighting bake though since the asset will be referenced again after each bake.

Thanks a lot for the reply , I was actually losing my hope that i can never actually run it on devices below 8 gb ram. Im feeling calm that you replied.  But when I delete that 370 mb lighting data asset and play my scene , and click on lighting 1 or lighting 2 , lightmaps switches but they arent properly arranged on the gameobjects at all , random lightmap scales/arrangement on the renderers and I get a message 

> You can indeed remove the initial lighting data asset reference from the scene. Just go to the lighting window and click the lighting data asset reference and press delete on your keyboard. This will not include those data when loading the scene (ambient light will be applied) and then only load the lighting data when using the lightmap switching tool. You will have to do this after every lighting bake though since the asset will be referenced again after each bake.

I have already did it several times , but whenever I switch between lighting 1 or lighting 2, the lightmaps indeed loads, but do not get arranged correctly on the objects , and I get an error message , But when I keep the reference of that 370 mb lightmap data asset initialy befolre playing , everything works fine, that's why im finding a way to get rid of it somehow, i mean not to get required to put the the huge lightmap data asset on the reference box iniially before polaying or building.
 here are some screenshots to show you.  
 
![a](https://github.com/user-attachments/assets/e6630d97-6c01-4f6d-97de-024f391c125f)
![b](https://github.com/user-attachments/assets/2035df66-6ec4-4b2d-ae86-ad69431762fa)
![c](https://github.com/user-attachments/assets/3e2d8f2f-d380-483e-a01b-0259a1c44052)
![d](https://github.com/user-attachments/assets/99e3ebab-e03a-4d26-971c-7b05fe3708a5)

**Comment by JAMS49** [comment]
> I could include this in the tool, but I'm not sure when. I would need time to test it.

Thanks a lot , It's be a big life saver for memory , I dont wanna break your valuable time, I would just eagerly wait for a solution, it'd be very kind of you buddy. and I have lightprobes same and unchanged in all the scene, i mean constant number and same positions. I just wanna get rid of that 370 mb extra elephant  crashing my build.  and I have a last question, as I have a big openworld scene, does unity loads all the lightmaps in memory during playtime? i mean i have total 210 lightmaps total size 292 mb, I divided the whole scene in 64 chunks that enables and get disbaled based on player's position , not everywhere i need those all 210 lightmaps , maximum 10 lightmaps are required in each chunk , somewhere it';s just 2-3 that covers all the renderers in that chunk becauise i have used baked tag on the objects of each chunks to ensure that the objects within the chunks doesnt share any lightmap of another chunk's objects , thus 64 baked tags , and lightmaps are well arranged in 64 chunks objects , any way to just load the lightmaps of the objects of that specific chunks only ? instead of loading whole 210 lightmaps on the play? that would be a huge saving of memory , Im so grateful for your reply. Thanks )

**Comment by JAMS49** [comment]
> I could include this in the tool, but I'm not sure when. I would need time to test it.

Hey any update?

**Comment by laurenth-personal** [comment]
Hello, after a bit of testing it looks like I could work around the initial lighting data asset easily for light probes. For lightmaps I would need a bit more work.
Would an intermediate fix for lightprobes only be useful to you ?

**Comment by laurenth-personal** [comment]
Forget that, the lightmap setup was buggy due to some unfinished code. It should now be fixed. There is no new release on package manager yet, the changes are only on the github repository's master branch.
I'll close this when I'll have time to make a proper release

**Comment by JAMS49** [comment]
> Forget that, the lightmap setup was buggy due to some unfinished code. It should now be fixed. There is no new release on package manager yet, the changes are only on the github repository's master branch. Can you test if it works for you ? I'll close this when you confirm the fix and when I have time to make a proper release.

lightmaps are swapping and scaling correctly on the renderers now , also the lightprobes and environment reflection also working correctly , all without putting the static scene lightmap.data asset on the reference of baked lighting tab. so I thought that I can now just delete the lightmap.data asset ., so I did., but then I get one problem, the lightmap swapping works correctly , also the reflction too , but the only problem left is the lightprobes arent loading at all , are lightprobes still dependent on that lightmap.data asset that I have deleted?  thanks a lot , at least now the scaling of the lightmaps are correctly working )) hooyah!
![sw](https://github.com/user-attachments/assets/731a3208-2dc1-43b1-b30f-939cb0a77cc0)

**Comment by laurenth-personal** [comment]
Hello, thanks for the feedback. Yes the probes were still contained in the lightingdata asset, this is now fixed and they will be stored in the scene.

**Comment by JAMS49** [comment]
> Hello, thanks for the feedback. Yes the probes were still contained in the lightingdata asset, this is now fixed and they will be stored in the scene. I tried your repro steps and my change fixed it, but can you please confirm it works for you too ?

Huge thanks buddy !!! at last it works 100% properly as expected , the lightmap swapping , accurate scaling on the renderers , swapping of lightprobes and reflections everything works just fine without the need of that primary lightmap.data asset . I have deleted that entire lightmap.data asset from the project and everything just works cool without it , neat! It saved me a 370 mb memory footprint which is huge for mobile games. Thanks a lot again, I can confirm that everything is fine now. It'd be better to update it in the package manager finally.

**Comment by laurenth-personal** [comment]
Hello, I'll start preparing the new version.

**Comment by laurenth-personal** [comment]
The new version is up on open upm. Thank you for your patience and your feedbacks 👍

**Comment by JAMS49** [comment]
> The new version is up on open upm. Thank you for your patience and your feedbacks 👍



> The new version is up on open upm. Thank you for your patience and your feedbacks 👍

Hey , again there is problem with the scaling of the lightmaps on the renderers, lightmaps are not arranged properly on the objects at all. It happens when the initial lightmap.data asset is on the reference . and when I do that without keeping it ,. lightmaps arent placed on any objects at all i.e the whole scene has absolutely zero lightmaps. any clue what's the problem?

**Comment by JAMS49** [comment]
> Hello, I'll start preparing the new version.

I have tested it in a new empty project , The scaling is not working somehow , here is an warning I get in the console
![dg](https://github.com/user-attachments/assets/225f8b9e-673e-4662-8324-15c35782a468)

Im sorry for the hassle , but the system worked very well in your master repository , but not working in other projects

**Comment by JAMS49** [comment]
probably it's something with the project setting , I will look into it

**Comment by laurenth-personal** [comment]
This is caused by static batching being enabled in your project.When using my test project it’s disabled, but if you import the package in your project you have to disable it yourself (project settings/player) This is only problematic if you have different lightmap resolutions on the different lighting scenarios. If the resolution is always the same you don’t need to apply renderer scale and offset.Le 24 août 2024 à 09:13, Jubaer Al Meraj ***@***.***> a écrit :﻿
probably it's something with the project setting , I will look into it

**Comment by JAMS49** [comment]
> This is caused by static batching being enabled in your project.When using my test project it’s disabled, but if you import the package in your project you have to disable it yourself (project settings/player) This is only problematic if you have different lightmap resolutions on the different lighting scenarios. If the resolution is always the same you don’t need to apply renderer scale and offset.Le 24 août 2024 à 09:13, Jubaer Al Meraj ***@***.***> a écrit :﻿ probably it's something with the project setting , I will look into it —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

I have just tested a scene with two cubes , and lighting 1 scene has a directional light and lighting 2 scene has a point light , both resolutions are same and baked size too, still not working with static batching checked. previously I didnt have this problem I was aware that I have to carefully set up the lighting so that it comes out with same resolution , size and same lightmap scaling despite of different lighting setup, previous version worked properly checking the static batching in project setting, now in that same scene, it show that scaling issue due to the static batching checked. even in my little test with two simple cuibes, same lightmap resolution , the lightmaps are misarranged. Im extremely sorry for the hassle but im afraid other users will face the same trouble even if they properly set up scenes with same resolution and renderer scaling .

**Comment by laurenth-personal** [comment]
Can you try disabling "Apply lightmap scale and offset" ? that should  prevent the warning

**Comment by JAMS49** [comment]
> Can you try disabling "Apply lightmap scale and offset" ? that should prevent the warning. That being said, I might need to do something else to support this + no lighting data asset

Hi I tried what you said , still it fails to arrange the lightmaps properly in the scene objects . even if I have the initial lighting data asset in the reference , still broken arrangement . I have static batching unchecked too, and not using static batching utility either . I reset up the light swapping system in the scene, still same failure . But reflection and light probes are working correctly I have checked them , according to my idea , i know ehere is shadow and lights , I did check the light probe, it's working fine , But only the problem is now misarrangement of lightmaps. It's now worse than previous version, the previous version at least could arrange the lightmaps , light probes an reflections properly with the need of lighting data asset and even static batching checked because my 2 lighting scenerio use same lightmap resolutions and same object scaling values lightmap atlas. in this latest version lightmap isnt arranged corectly even if I disable static batching . I think there is something a bit wrong. 
![ds](https://github.com/user-attachments/assets/2ebd48e4-9a9f-4cf9-aafb-9f619e9f5bd9)
![ww1](https://github.com/user-attachments/assets/5e4d8d9e-05cf-4e68-a9aa-1029d2b20a1a)
![ww](https://github.com/user-attachments/assets/277b1d9d-10dc-49ed-be03-a0d33f87dd7e)

**Comment by laurenth-personal** [comment]
Hello, sorry about that. I see you are using terrain, do you use several terrains ? That part of the code is pretty bad.

**Comment by laurenth-personal** [comment]
Hello, I am publishing a new version. This should help with terrain or multiple terrains.
Also I found when there is no lighting data asset, lightmap scale and offset are reset on all renderers.
I have not found a solution for this, I don't know if there is one besides not using static batching.

**Comment by JAMS49** [comment]
Im not actually using any terrain here, what you see are actually meshes
not any terrain itself. But you can also test with something little, like
two or three cubes, same resolution, you can clearly see how it's not
working with static batching checked. and Yeah, Im not using terrain at all.

**Comment by laurenth-personal** [comment]
Hello, I have tried on a more recent version of unity (2022+) and with
several light maps (4 lightmaps). I can see the indices of the light maps
are stored incorrectly in the different scenarios.
A dirty workaround could be to increase the maximum size of your light maps
if it's possible to fit all in one.
I would like to investigate this issue but I don't have the time before the
weekend.

Le mar. 27 août 2024 à 06:02, Jubaer Al Meraj ***@***.***> a
écrit :

> Im not actually using any terrain here, what you see are actually meshes
> not any terrain itself. But you can also test with something little, like
> two or three cubes, same resolution, you can clearly see how it's not
> working with static batching checked. and Yeah, Im not using terrain at
> all.
>

**Comment by laurenth-personal** [comment]
Hello, I managed to reproduce some issues with the lightmap indices, and some issues I think caused by the back tracking of the current lighting scenario.
These 2 should be fixed in the new version and I hope those were the issues you were having.

In the end, I think it's not possible to totally remove the lighting data asset because the lightmap scale and offset of the renderers seem to be stored there and not on the meshrenderers.
In the editor it's possible to apply lightmap scale and offset on awake before static batching is applied, but in the build the assets are probably already batched together when the scene loads and it's impossible to change anything, if the lighting data asset is not there they will just use the default lightmap scale and offset for all the objects.

**Comment by JAMS49** [comment]
Hi,  Sorry for the late reply,  I was curious what happens if static
batching isnt setup in build. Instead of it, Im using static batching
utility which means, I will batch those in Runtime when only needed. but
Before that, it will be okay without lightmap data asset?

**Comment by laurenth-personal** [comment]
I have exposed a new public function that should help with runtime static batching : ApplyDataRendererInfo(int index)
You can either call this before runtime batching, or LoadLightingScenario.
That way, your renderers have the correct lightmap scale and offset before doing the batching.
Hopefully it will bake the lightmap scale and offset in the batched geometry as it does when there is a lighting data asset.

**Comment by JAMS49** [comment]
Thanks a lot, It seems to be a great solution,  I will check it out.)

**Comment by JAMS49** [comment]
Hi , Im back to work , I have updated the package but the "store" button is
missing. Generally I avoid rebaking the lightmap which took me almost 23
hrs to bake the whole world , so, I just place the baked lightmap data
asset on the reference and click on store, the lightmap and other datas are
thus cached as expected. , can you please add that button?

**Comment by laurenth-personal** [comment]
Hello, I'm sorry to read that you're missing the store button. I've always seen it as a useless step but needed workaround because in much older versions of unity i think the callback after the asynchronous bake was not reliable.
I can add an option to restore it but I can't make a new version this weekend.
The method for storing is public though so you can use a unity event or another script to call it and pass it the lighting scenario index.
If you're using unity event make sure you switch to the mode that also runs in the editor.

**Comment by JAMS49** [comment]
Hi laurenth , sorry I was actually in hospital for weeks , I have opened my project today and messed with lots of things, I admit that  I gotta keep batching disabled to have the swapping properly without the need of lighting data asset , I dont know why latest versions are still giving weird scaling and lightmap arrangement even without and batching enabled at all (disabled in player setting , and no scri[pt is used for any batching). 
But surprisingly version 3.1 gave wonderful result , firstly it stores the lightmap positions and scales properly and without requiring lighting data asset , I can easily swap between the lightmaps . Im sorry, at the first time of this convo, I didnt tried keeping static batching off, but this time I tried and got proper result 

Still, !! the only one thing is the missing lightprobes only. as you told me at the first time of your convo . Can You keep everything same just fixing the lightprobes problem in version 3.1? because, when I update the versions, lightprobes works well, but lightmap arranements are unexpectedly corrupted, I have tested them all. I dont know why. Please, it;s my last request to you. just need version 3.1 , only fixing the missing lightprobe problem, nothing more.

**Comment by JAMS49** [comment]
I tried the commits which you initially modified , but still, the closest upgrade from version 3.1 is storing the lighting , no static batching and when switching , I see weird arrangement of lightmaps . This is clueless and saddening part, I wish you were here

**Comment by laurenth-personal** [comment]
Hello, I just read your messages.
I am curious about something, did your case stop working already in version 2019.4.1 compared to 2019.3.1 ?
I'll investigate what changed after that.

**Comment by JAMS49** [comment]
Okay , keeping static batchings off , I have done all these tests. 
First of all, I have tested with this package version 2019.3.1 
1) it works perfectly without lighting data asset , arranges the lightmaps in the scene accurately . But no lightprobes. 
(the distant green building lod is set for lightprobe, but it's black cz, lightprobes are missing)

https://github.com/user-attachments/assets/877cde2c-0962-4d11-86ca-f29a31561b0a

2) But the build shows different behaviour on mobile , in editor , lightmaps when switched, arranged in the scene properly. but in mobile , it doesnt happen, lightmaps dont get arranged on the renderers . as you can see in this video 

https://github.com/user-attachments/assets/fb8ec678-9027-4f6e-b758-5a0085aae971

I did tried to modify a bit following this commit 
![df](https://github.com/user-attachments/assets/83dda6e2-8a96-4860-b299-b1499fb79a18)
![gh](https://github.com/user-attachments/assets/acabbc23-f696-49f3-aea5-e3655595d5c9)

still I get the same result on builds.

Now , after upgrading the package to newer version (I tried all the versions upper than 2019.3.1) . I did all the same procedure , but , when hitting play and switching the scenerio, absolutely no lightmaps in the scene , But yeah , lightprobes are working. You can see this video here ;


https://github.com/user-attachments/assets/e17d145b-e4fe-409b-a517-da12d34db81c


I have also tried to see keeping the initial lighting data asset assigned in the reference . and the result ;


https://github.com/user-attachments/assets/a87dcd31-33f3-4b91-aae9-4207d7b88cb9


so , Overall, It's kind of frustrating 

My thought is , the package version of 2019.3.1 works well, just somehow lightmaps arent arranged on build properly , and lightprobes are just missing . these two problems need to be fixed from that version. and everything will be just perfect I guess. 

One Good news is , when I was testing with package version 2019.3.1 , I was able to use static batching utility perfectly after switching between lightmaps , the static batching worked properly without any lightmap misarrangement . yeah, on start ,you must keep static batching off , but when you hit play , and switch between lightmaps, then you can pefectly use static batching with script and batching perfectly works with proper arrangement of lightmap on the scene objects. that's great I have discovered on version 2019.3.1 . 

But those two issues 1. misfitting lightmaps on builds 2. Missing lightprobes. 
if these are fixed properly , The package will be a wholesome tool for this big purpose of switching lightmaps and getting rid of huge lighting data asset due to large scene baking and also having static batching properly in that way. overall a big perfecto>

Thanks a lot to read upto here)

**Comment by JAMS49** [comment]
Well, forget all of them , I have tested in the latest version of this package , managing the 'store' button to do the procedures.

Everything works well in the editor ,such as correct lightmap arrangements, lightprobes are loaded , everything is okay , swapping between day and night works well. All without the help of lighting data asset. here you can see an example video;


https://github.com/user-attachments/assets/78db753b-1996-49fd-9ef9-0f6d78f7db9e


But the build shows different behaviour , when switching lightmaps, lightprobes are present and swapped correctly , but there is no lightmap in the whole scene at all. I checked the editor log of the build, all the lightmap textures are included inside the build, but still, everywhere is dark when I switch. here is a video of the build. 


https://github.com/user-attachments/assets/1da4df17-4211-452b-b2ff-9aaceeb6a34b


Im clueless, what;s the reason behind it .

So, that's the latest case , on the latest package version. Can You do something about it ?

**Comment by laurenth-personal** [comment]
I can do what you requested : 2019.3.1 + the lightprobe code, I checked it's quite simple to change. I won't be able to test it very well this week but maybe it works for you.
The other idea I have is that maybe the fact that you're using LODs and meshes might not be available when you start the level affects the lightmapping. I'd have to add LOD groups in my test case to check and that sounds like a good thing to test anyway, but again I can't test this thoroughly this week.

**Comment by JAMS49** [comment]
> I can do what you requested : 2019.3.1 + the lightprobe code, I checked it's quite simple to change. I won't be able to test it very well this week but maybe it works for you. The other idea I have is that maybe the fact that you're using LODs and meshes might not be available when you start the level affects the lightmapping. I'd have to add LOD groups in my test case to check and that sounds like a good thing to test anyway, but again I can't test this thoroughly this week.

No problem, Im always here to test and inform you , as I have a pretty big scene, it will be a good arena to test this tool.

**Comment by laurenth-personal** [comment]
I 've released a 2019.3.2 version with just the lightprobe changes because that's the easiest thing to do for me right now.

**Comment by JAMS49** [comment]
> I 've released a 2019.3.2 version with just the lightprobe changes because that's the easiest thing to do for me right now.

I was getting this error 
![dd](https://github.com/user-attachments/assets/04a27000-b187-4761-ac1c-0aef074bd87a)

later I added using UnityEngine.Serialization ; on the script to fix the error. But after that I get this below 
![r1](https://github.com/user-attachments/assets/4116bbc0-ac9e-464b-9339-410facd4c3b7)
![r2](https://github.com/user-attachments/assets/ca2a0fa8-e9a3-4551-948f-82a1cab199be)

is there any typo ?

**Comment by laurenth-personal** [comment]
Oh, looks like I forgot a commit in the release >_<

**Comment by laurenth-personal** [comment]
It's probably simply missing a line like 
var data = lightingScenariosData[index];

**Comment by JAMS49** [comment]
Okay after a long investigation in package version 2019.3.1, I have diagnosed the actual problem behind the lightmap misarrangement in the build.  It is not actually for LOD or missing mesh I have tested.  Rather the actual reason is surprising.
 

In editor everything works fine. After searching a bit, I've found that The problem can be reproduced in editor by unchecking the "Generate lightmap UV" in mesh import setting. When I toggle this off, I get that same misarranged lightmap which I was getting in the build. So what i can understand from this is - the data that is created by checking "Generate lightmap UV" on mesh import setting in the editor, is not included in the build. That;s why I get misarranged lightmaps on the mesh. Haha.

I can confirm that this is the actual reason behind it.


In editor ; 
![a ](https://github.com/user-attachments/assets/7efe590e-d175-44a4-bab4-6ba3d278b6f7)

In build ;
![b ](https://github.com/user-attachments/assets/e2e7dfd3-6f4c-43d4-b5f5-29cbe74d3885)

In editor after unchecking the "Generate Lightmap UV" on mesh import settingl
![c ](https://github.com/user-attachments/assets/18ba5da4-1a84-49a7-bab6-9a24fff15d5c)


So, This is the case. What do you think , is it possible to fix actually?

**Comment by JAMS49** [comment]
Okay , I have also got the solution on misarranged lightmaps in the build. Actually Unity sometimes blow your second uv of the mesh on the build. You need to disable "Project Settings → Player → Other Settings → Optimize Mesh Data." 
and the lightmap UV data are packed properly on the build and You will get proper lightmaps arrangement on the mesh . without even needing the lighting data asset. 

Now I will check out your fix on lightprobes and inform you. This is the last task left now.)

**Comment by JAMS49** [comment]
I checked 2019.3.2 and fixed some errors in the script: 

Hurray !!!! Lightmaps and Lightprobes are working fine in the build without lghting data asset.!!!!!!! 

But the main concern was to get rid of that two 370+370 mb lighting data assets which sucks the memory. Now using this tool, I see it's at a time loading all the lightmaps textures and lightprobe data of both day and night  at the same time in memory even if I dont need when only day scene or night scene is active. Is there any way to keep the night scene's lightmap textures and lightprobes unloaded from memory when only the day scene is active? 

The memory is flooding with both of them. 
![SharedScreenshot](https://github.com/user-attachments/assets/f31cdec7-996f-4c46-b422-5e1da2a32a64)

**Comment by laurenth-personal** [comment]
The tool doesn't currently support it.
What happens is that the component references the datas for all the scenarios, so unity loads the components and its dependencies with the scene.
It takes memory but makes the switch fast.
If you don't care about having some loading when switching it might be possible, but I don't really know how.

The changes I made in the 2019.4 versions should allow using asset bundles, and these assets can be used to "discover" a lighting scenario at runtime. It's not directly referenced by the scene so not loaded from the start. 
It hasn't been tested a lot and I think that even if you use this, at some point you will have both scenarios loaded in memory. Then unloading will need to be called for the unused asset.

**Comment by JAMS49** [comment]
> The tool doesn't currently support it. What happens is that the component references the datas for all the scenarios, so unity loads the components and its dependencies with the scene. It takes memory but makes the switch fast. If you don't care about having some loading when switching it might be possible, but I don't really know how.
> 
> The changes I made in the 2019.4 versions should allow using asset bundles, and these assets can be used to "discover" a lighting scenario at runtime. It's not directly referenced by the scene so not loaded from the start. It hasn't been tested a lot and I think that even if you use this, at some point you will have both scenarios loaded in memory. Then unloading will need to be called for the unused asset.

I understand the point,  But I didnt realise at all that, Lightprobes data will become this much big in my scene. I think there is no other way but to rebake the probes. unfortunately I've forgot all the lightmapper setting and scale value on my prefabs. It might result unwanted new lightmap result.
Do you know any possible way to only bake the lightprobes in the scene? based of existing lightmaps?
If not possible, probably I need to find any alternative similar to light probe functioning. 
Thanks.

**Comment by laurenth-personal** [comment]
It's not possible to only bake lightprobes as far as I know.
You can compress and stream lightmaps, but I don't think there is much you can do to lower the weight of the lightprobes.

**Comment by JAMS49** [comment]
I see , whatever , Thanks a lot for the support , it's really a great tool buddy , I would recommend the package version 2019.3.1 to make the primary package, because it works in all the way . Again, Thank you soo much for being with me till this. Great tool.
