### ISSUE TITLE
Bakery support?

### ISSUE THREAD

**Issue by JasonWeise** [laurenth-personal/lightmap-switching-tool#40]
This looks to be an amazing solution to a need I have for swapping between a few lighting scenarios in Unity, but as I use Bakery and not the built in lightmapper is there an easy way to integrate with Bakery.

I think I might be able to get away with baking multiple times with Bakery and then remove all but lights in the "lighting" levels but it would be great if this package could more easily support baking with Bakery.

Is this possible at the moment or in the works?

**Comment by laurenth-personal** [comment]
Hello,
I know Bakery is very popular but I don't own it myself so I'm not too sure what it would take to support it. 
For example I know it has more lightmap modes like sh lightmap that sounds very cool, but that's probably implemented in a custom way that would need totally different code.
I don't plan to support it myself, but if someone wants to work on it and make a pull request I'll definitely look at it and try to integrate it.
