### ISSUE TITLE
Unity 6 Support

### ISSUE THREAD

**Issue by JasonWeise** [laurenth-personal/lightmap-switching-tool#41]
Hi 

I have decided to move from Bakery to Unity GPU Lightmapper so I can try out this lightmap switching tool and I have found that the baking never works as shown in the readme.

I perform each of the steps and everything appears to bake correctly, but when I try to switch lighting scenarios in playmode, an error is shown in the console saying the current index couldn't be unloaded. (this is before any lighting scenario is loaded)
I have checked everything is in the correct places in the LevelLightmapData, and it all appears ok, but I do notice the LightmapScenario fields get cleared as soon as you enter play mode.

Before I dig too much deeper, is this lightmap switching tool compatible with Unity 6 (and URP)?

Thanks for all your hard work, I am really hoping I can get this working.

**Comment by JasonWeise** [comment]
Further to the above, if it supposed to work fine in Unity 6, it would be great to get a video tutorial on how to setup a basic scene with two or three lighting scenarios.

I see there is a quick start video, but it mostly just shows how to load the demo scene, not how to actually start from scratch.

Thanks as always.

**Comment by laurenth-personal** [comment]
Hello, i have not tested the tool in unity 6 yet.
I have never seen an error line the one you mention so maybe something has changed.
I have previously tested it with URP and it worked.
In unity 6 you can also use adaptive probe volumes to switch lighting. I don't know how good is the documentation but it should support switching and even blending lighting scenarios.

**Comment by laurenth-personal** [comment]
I'll try to run some tests this weekend.

**Comment by JasonWeise** [comment]
Thanks for taking the time to have a look, I am hoping it is something I am not doing correctly when trying to bake the scenes and then switch in playmode, but I have tried numerous times now since putting in this github issue and cannot get it to work.

I had thought about using Adaptive Probe Volumes but I am developing for Quest 2/3 standalone VR and didn't think they worked on mobile/mobile vr. Maybe I might need to research a bit further on this one if you find Unity 6 won't work in your assets.

Once again thanks for taking the time and I look forward to hearing back :)

**Comment by laurenth-personal** [comment]
Hello, here is a [video ](https://drive.google.com/file/d/19YsWl-rD-s2akd87UENzj4woynY13-Yh/view?usp=sharing)for a setup from scratch in unity 6.
It uses the last version as I had to do some fixes.
